### ISSUE TITLE
create jenkins jobs that initializes repository

### ISSUE THREAD

**Issue by sgratzl** [phovea/deployment_scripts#1]
* labels
* protect title + url
* define repository owner in readme
* set teams, e.g. add bots

could also be part of ? phovea-init? in which the repository is created and initialized

see https://developer.github.com/v3/repos/#create

**Comment by mstreit** [comment]
@sgratzl, obsolete? or do we want to have the same for circle CI?

**Comment by sgratzl** [comment]
same argument: circleci is a building tool only, while you can create parameterized jobs using Jenkins, e.g. you add as an argument the repo and it will does its job
