### ISSUE TITLE
create admin app

### ISSUE THREAD

**Issue by sgratzl** [phovea/deployment_scripts#13]
that directly communicates with Github and AWS to automatize certain tasks

tasks like
 * #2, #5 
 * setup Github repo and initialize it: tags, labels, ...
 * setup Circle CI task
 * setup product
 * create task definition in AWS
 * create repose.g. registering a new app in AWS for deployment
 * register domain in AWS
 * add it to the list of caleydoapp.org listed apps
 * ...

**Comment by mstreit** [comment]
@sgratzl, obsolete? or do we want to have the same for circle CI?

**Comment by sgratzl** [comment]
circle ci is a building tool only. So there is no way to script something like that. Tho it still would be nice to have something similar

**Comment by mstreit** [comment]
OK, then let's close this and keep the goal in mind for the future.
