### ISSUE TITLE
add another service to landing page

### ISSUE THREAD

**Issue by sgratzl** [phovea/deployment_scripts#14]
**Task**
Add another service and make it accessible with a subdomain (e.g., taco.caleydoapp.org).

**Instructions**
1. Go to CloudWatch -> Logs
1. Create a new log group from the actions dropdown and name it `app_<Name>`

.

1. Go to Route 53 -> Registered domains -> caleydo.org ->Manage DNS -> caleydo.org
1. "Create Record Set" with subdomain name, Type: `A - IPv4 address`, Value: `<cluster ip>` -> Save Record Set

.

1. Go to EC2 Container Service -> Task Definitions
1. Create a Tasks Definition (or if possible, copy a previous one) ...
1. Set the *web container* (in *Container Definitions*) to a free host port
   ![port mapping](https://user-images.githubusercontent.com/5851088/29174211-e56723f2-7de5-11e7-940f-3964ea6e6b98.png)
   * 32791 ... lineup
   * 32792 ... bob
   * 32793 ... taggle-daily
   * 32794 ... ordino-daily
   * 32795 ... gapminder
   * 32796 ... stratomex
   * 32797 ... tourguide
   * 32798 ... pathfinder
   * 32799 ... gapminder-retrieval
   * 32800 ... domino
   * 32801 ... lineage
   * 32802 ... taco
   * 32803 ... thermalplot
   * 32804 ... ordino
   * 32805 ... ordino-retrieval
   * 32806 ... taggle
   * 32807 ... taggle-outdated ("taggle1")
   * 32808 ... tourguide-ordino
   * 32809 ... ordino-taggle
1. For all containers use the new log group as log driver (in *Log configuration*)
    ![log driver](https://user-images.githubusercontent.com/5851088/29174637-2ab360aa-7de7-11e7-9c0a-99327586bb45.png)
1. If necessary, change the path to mounted volumes to a new directory
1. Save/Create the task definition for this app
1. Create a new task revision of `caleydoapp` ...
1. Add a new environment variable within nginx: `PHOVEA_APP_<NAME>` `<Name>;<Domain>;cluster:<Port>`
1. Save/Create the task definition for `caleydoapp`

---

**How to access other links on the same cluster instance**
use private ip of the cluster instance and a free port cluster/10.0.1.172

---

*Post was edited by @thinkh on 2017-08-10*

**Comment by mstreit** [comment]
Moved to https://wiki.datavisyn.io/phovea/deployment
