### ISSUE TITLE
Setup and configure mail forwards

### ISSUE THREAD

**Issue by thinkh** [phovea/deployment_scripts#16]
For forwarding mails to Caleydo mail addresses we use the [aws-lambda-ses-forwarder](https://github.com/arithmetric/aws-lambda-ses-forwarder). It uses the [Amazon Simple Email Service (SES)](https://aws.amazon.com/en/ses/). Incoming mails are stored in the S3 bucket *caleydo-email-forwarder* and processed by the Lambda function *SesMailForwarder* (containing the configured *index.js* file). The S3 bucket is configured to store the mails for 30 days and then permanently remove them. 

## Add a mail forward

1. Open Amazon SES -> Rule Sets (under Email Receiving) -> View active rule sets
2. Open rule set *SesMailForwarder*
3. Add another recipient to the list (note: the domain be caleydo.org)
4. Save the rule
5. Go to Email Addresses (under Identity Management) -> Verify a New Email Address
6. Enter the same email address as before
7. Go to Amazon S3 -> caleydo-email-forwarder/SesForwarder
8. Download the file with the most recent timestamp
9. Open it on your computer with a text editor
10. Open the contained registration link in your web browser to verify the mail
11. Make sure that the mail address is verified in Amazon SES -> Email Addresses 

Follow with the next section to add recipients to forward to. 

## Add/remove recipients to a mail forward

1. Open AWS Lambda -> Functions -> SesMailForwarder
2. Add FROM mail addresses and their respective forwards (TO) to the `forwardMapping` property in the configuration
3. Save the function

**Comment by mstreit** [comment]
Moved to https://wiki.datavisyn.io/edit/phovea/deployment
