### ISSUE TITLE
setup repo in circle ci

### ISSUE THREAD

**Issue by sgratzl** [phovea/deployment_scripts#17]
Set-Up Repo in CircleCI
=======================

regular repo
------------

1. Advanced Settings -> Auto-cancel redudant builds: `on`
1. Chat Notification: enter slack url
1. Checkout SSH key -> add user specific one and remove old -> preferable done via the `caleydo-bot` account to avoid own one
 
product repo
------------
 
1. see regular
1. AWS Permissions
   PRIVATE
1. Environemnt Variables: 
   * `DOCKER_AUTH`: PRIVATE
   
enable daily build trigger
--------------------------

1. go to https://eu-central-1.console.aws.amazon.com/lambda/home?region=eu-central-1#/functions/TriggerDailyCircleCIBuild?tab=code
1. add to the list of projects `dict(project="Caleydo/<product>",branch="<branch>")`

**Comment by mstreit** [comment]
Moved to https://wiki.datavisyn.io/phovea/deployment
