### ISSUE TITLE
create jenkins job that add all stuff needed for a new app

### ISSUE THREAD

**Issue by sgratzl** [phovea/deployment_scripts#2]

**Comment by sgratzl** [comment]
e.g. for gapminder

tasks to create new app: gapminder

1. Route53: create new record set in caleydo.app hosted domain: 
  gapminder.caleydoapp.org 	35.157.100.192
1. Jenkins: create new job based on another product
  gapminder_product -> change github url and pipeline repo to target repo
1. Jenkins: create update job: update_gapminder
  fix dependency to gapminder_product
1. define a new port in https://github.com/phovea/deployment_scripts/blob/master/docker/phovea/phovea_nginx/README.md
   32795 ... gapminder
1. EC2 Repositories -> Create Repositories
  caleydo/gapminder/gapminder
  caleydo/gapminder/gapminder_server
1. EC2 Task Definition: caleydoapp
  add environment variable: 
   ```json
	{
		"name": "PHOVEA_APP_GAPMINDER",
		"value": "Gapminder;gapminder;cluster:32795"
	}

   ```

1. EC2 Task Definition -> Create Task definition: gapminder
   ```json
	{
	  "family": "gapminder",
	  "networkMode": "bridge",
	  "containerDefinitions": [
		{
		  "name": "web",
		  "portMappings": [
			{
			  "hostPort": 32795,
			  "containerPort": 80,
			  "protocol": "tcp"
			}
		  ],
		  "links": [
			"api"
		  ],
		  "image": "922145058410.dkr.ecr.eu-central-1.amazonaws.com/caleydo/gapminder/gapminder:daily",
		  "logConfiguration": {
			"logDriver": "awslogs",
			"options": {
			  "awslogs-group": "app_gapminder",
			  "awslogs-region": "",
			  "awslogs-stream-prefix": "web"
			}
		  },
		  "memoryReservation": 128
		},
		{
		  "name": "api",
		  "image": "922145058410.dkr.ecr.eu-central-1.amazonaws.com/caleydo/gapminder/gapminder_server:daily",
		  "logConfiguration": {
			"logDriver": "awslogs",
			"options": {
			  "awslogs-group": "app_gapminder",
			  "awslogs-region": "",
			  "awslogs-stream-prefix": "api"
			}
		  },
		  "memoryReservation": 256
		}
	  ]
	}
   ```

1. EC2 cluster: stop and start caleydoapp with the new revision
1. Jenkins: run stop

**Comment by mstreit** [comment]
moved to https://wiki.datavisyn.io/phovea/deployment
