### ISSUE TITLE
Create a new subdomain forward

### ISSUE THREAD

**Issue by thinkh** [phovea/deployment_scripts#5]
**Task**
Create a new sub-domain for *.caleydo.org that forwards to a certain URL.

**Instructions**
1. Route 53 -> Registered domains -> caleydo.org ->Manage DNS -> caleydo.org
2. "Create Record Set" with subdomain name, Type: `A - IPv4 address`, Value: `<cluster ip>` -> Save Record Set
3. Elastic Container Service -> Task Definitions -> caleydoapp
4. Select `caleydoapp:<revision number>` and "Create new revision"
5. Select container `nginx` and add a new "Env Variables"
    ```json
    {
      "key": "PHOVEA_FORWARD_<SUBDOMAIN_NAME>",
      "value": "<name>;<subdomain_name>.caleydo.org;<forward_url_without_http(s)>"
    }
    ```
7. *Update* (closes the nginx dialog) and *create* new revision of task definition
8. Back in task definitions, select old revision `calyedoapp:<old_revision>` and *deregister*
9. Switch to EC2 Container Service -> Clusters -> caleydo -> Tasks
10. Select task with task defintion `calyedoapp:<old_revision>` and *stop* that task
11. *Run new task* with `calyedoapp:<new_revision>` (no need to configure other options) -> *Run Task*
12. Wait a minute until the new task is *running*
13. Check if the new subdomain is connected

Note that the caleydoapp nginx server is responsible for:
1. making *.caleydoapp.org available
2. forwarding to a different URL

**Comment by mstreit** [comment]
Moved to https://wiki.datavisyn.io/phovea/deployment#create-a-new-subdomain-forward

**Comment by mstreit** [comment]
@thinkh, I've followed the tutorial for creating the redirect of phovea.caleydo.org. Worked like a charm. Thanks.
